### ISSUE TITLE
CocoaPods support?

### ISSUE THREAD

**Issue by Pitometsu** [ReactiveCocoa/ReactiveObjC#10]
Would you add `ReactiveObjC` to `CocoaPods`?

**Comment by mdiep** [comment]
If someone wants to open a PR that adds support, I'm okay with adding it.

**Comment by Pitometsu** [comment]
Ok, I'm glad to make it. However, I can't see any tags or version information, so not sure about which one should I choose for pod. Also according to [contributing guide](https://github.com/ReactiveCocoa/ReactiveObjC/blob/master/CONTRIBUTING.md), as I understand, I should ask questions like that in slack room. Is it exist yet, and, if so, could you send invitation for me, please?

**Comment by mdiep** [comment]
I just released https://github.com/ReactiveCocoa/ReactiveObjC/releases/tag/1.0.0.

What email would you like to b invited at?

**Comment by Pitometsu** [comment]
Thanks, pitometsu@gmail.com.

**Comment by Pitometsu** [comment]
@mdiep, just created [PR](https://github.com/ReactiveCocoa/ReactiveObjC/pull/11/files)

**Comment by Pitometsu** [comment]
Thank you for attention.
