### ISSUE TITLE
deliverOnMainThread  cause crash: unrecognized selector

### ISSUE THREAD

**Issue by guoxiaoqian** [ReactiveCocoa/ReactiveObjC#102]
Hi,i want use  " [RACSignal deliverOnMainThread]" to schedule the signal on main thread,but it causes crash:

> 

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[RACDynamicSignal deliverOnMainThread]: unrecognized selector sent to instance 0x608000650650'

> 

i just do not know why ?

**Comment by erikprice** [comment]
You're sending that message to an object that is not a RACSignal.

**Comment by guoxiaoqian** [comment]
@erikprice   the message receiver is  an object of RACDynamicSignal, and RACDynamicSignal is a subclass of RACSignal，so why  the receiver  does not respond  "deliverOnMainThread" ?

**Comment by guoxiaoqian** [comment]
Oh，I see。。The reason is that  there are two libReactiveCocoa.a after updated by CocoaPods, and  the old libReactiveCocoa.a are linked  which do not support "deliverOnMainThread" 。
