### ISSUE TITLE
map: with remaining flag

### ISSUE THREAD

**Issue by nmccann** [ReactiveCocoa/ReactiveObjC#106]
Hi,

I've found that in converting my NSArray usage to RACSequence, I often have to convert the sequence back to an array to do some logic based on whether or not the current element is the last one. It seems to me that this is something that should be possible with RACSequence by looking ahead to see if there are any remaining elements. I would imagine the call-site to be like this:

```
[sequence mapWithRemaining:^(id value, BOOL hasRemaining) {
//Perform mapping based on hasRemaining state
}];
```

Whereas the implementation pseudocode would be:

```
if (sequence.tail) {
block(sequence.head, YES)
//Go to next iteration of map
} else {
block(sequence.head, NO)
//Mapping is done
}
```

I've been trying to implement this operator myself, and have looked at `combinePreviousWithStart:`, `flattenMap` and `bind` but can't quite figure out how I would do this kind of look ahead behaviour.

Any suggestions?

**Comment by erikprice** [comment]
It sounds like you just want to add a sentinel element to your sequence and then combine each element with its next value, checking for this sentinel to determine whether to expect any further elements.

```
id kPoisonPill = [[NSObject alloc] init];
RACSequence *end = [RACSequence return:kPoisonPill];
RACSequence *advanced = [[seq skip:1] concat:end];
RACSequence *final = [[seq zipWith:advanced]
    map:^(id val, id next) {
        return RACTuplePack(val, @( next != kPoisonPill ));
    }];
```

**Comment by nmccann** [comment]
That sounds like exactly what I want! Thank you for the quick reply!
