### ISSUE TITLE
Can't upload project to appstore.

### ISSUE THREAD

**Issue by coulCod** [ReactiveCocoa/ReactiveObjC#113]
I am use ReactiveObjC in my Objective C project. Everything was fine, but I recently decide to add few features on Swift. 
And now when I upload archive to itunce from xcode it give next error:

> iTunes Store operation failed.
Invalid Swift Support. The file StoryUa.app/Frameworks/ReactiveObjC doesn’t have the correct file type for this location. Ensure you’re using the correct file, rebuild your app using the current public (GM) version of Xcode, and resubmit it.

**Comment by mdiep** [comment]
Do you have `ReactiveObjC.framework` in `StoryUa.app/Frameworks`? Or some other file?

**Comment by coulCod** [comment]
@mdiep No, I have only "ReactiveObjC" folder with files in the StoryUa.app/Frameworks

**Comment by mdiep** [comment]
That's the issue. You haven't copied `ReactiveObjC.framework` into your app bundle correctly.

**Comment by coulCod** [comment]
@mdiep But I have ReactiveObjc.fragmework in Linked Frameworks and Libraries

**Comment by mdiep** [comment]
The framework still needs to be copied into the app bundle.

**Comment by coulCod** [comment]
@mdiep I am not undestand what is app bundle. Can you explain me, please.

**Comment by mdiep** [comment]
If you're using Carthage, you can make sure you've followed the instructions [here](https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos).

If you're using CocoaPods, they probably have similar instructions somewhere.

This isn't a ReactiveObjC-specific problem. Unfortunately I'm not able to provide more support than that.

**Comment by coulCod** [comment]
@mdiep I am add ReactiveObjC to my project as git submodule, as written in the README file to this repository.

**Comment by coulCod** [comment]
I found the mistake. That is was because I am not correctly done 5 step of **Importing ReactObjC Instruction**
There is written:

> Add ReactiveObjC.framework. RAC must also be added to any "Copy Frameworks" build phase. If you don't already have one, simply add a "Copy Files" build phase and target the "Frameworks" destination.

I understand that step as create "Copy Files" group and add "ReactiveObjC" folder as copy item. But I must to add ReactiveObjC.framework file. (not a folder)

Now I update my app successfully, Thank you @mdiep for support.
