### ISSUE TITLE
Xcode 9 prototype function issues

### ISSUE THREAD

**Issue by vitorhugomagalhaes** [ReactiveCocoa/ReactiveObjC#115]
Hi,

After enabling xcode 9 preferred build settings ReactiveObjc fails to build with several declaration is not a prototype errors.

The fix should be easy so should I submit a PR for this ?

Thanks,

**Comment by mdiep** [comment]
Yes please!

**Comment by vitorhugomagalhaes** [comment]
Thanks @mdiep

**Comment by vitorhugomagalhaes** [comment]
Sorry I didn't have the time to submit the fix. @developerforapple already did it and his waiting for PR to be approved.

**Comment by danielmartinprieto** [comment]
Hi! Is there a plan to merge these fixes?

**Comment by mdiep** [comment]
#115 has unaddressed feedback that needs to be fixed

**Comment by danielmartinprieto** [comment]
Sorry about that, I just saw your comment in that PR. Have you seen this one? https://github.com/ReactiveCocoa/ReactiveObjC/issues/122

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mdiep** [comment]
Yes, I've reviewed #122 as well. The fix there is actually wrong.

**Comment by crespoxiao** [comment]
😄
