### ISSUE TITLE
fromProtocol the subscribeNext block never called

### ISSUE THREAD

**Issue by programer001** [ReactiveCocoa/ReactiveObjC#116]
[[self.phoneNumberField.rac_textSignal rac_signalForSelector:@selector(textFieldDidEndEditing:) fromProtocol:@protocol(UITextFieldDelegate)]subscribeNext:^(id x) {
        
    }];
    self.phoneNumberField.delegate = self;
i do not know what can i do？

**Comment by faimin** [comment]
i think it should be 
```objc
[[self rac_signalForSelector:@selector(textFieldDidEndEditing:) fromProtocol:@protocol(UITextFieldDelegate)]subscribeNext:^(id x) {
    // do something
}];
```

**Comment by programer001** [comment]
thank you
