### ISSUE TITLE
xcode9 has many warnings

### ISSUE THREAD

**Issue by neng18** [ReactiveCocoa/ReactiveObjC#120]
example： ()  should be  Insert 'void'.

Please to fix.

**Comment by ikesyo** [comment]
I can't see any warnings. What is the version you are using?

**Comment by neng18** [comment]
xcode 9
![image](https://user-images.githubusercontent.com/6883455/30792553-c1b7b3d2-a1ed-11e7-8328-5c5b8fc871a6.png)

**Comment by faimin** [comment]
it's same to [#115](https://github.com/ReactiveCocoa/ReactiveObjC/issues/115),

```gcc
#pragma clang diagnostic ignored "-Wstrict-prototypes"
```
will be help

**Comment by neng18** [comment]
Thanks.

**Comment by ikesyo** [comment]
I'm saying about ReactiveObjC's version, not Xcode version 😅

**Comment by ikesyo** [comment]
Closing as a duplicate of #115.
