### ISSUE TITLE
use xcode9 archive find this error，help~

### ISSUE THREAD

**Issue by Jinzhengxuan** [ReactiveCocoa/ReactiveObjC#123]
error: unexpected duplicate task: CompileDTraceScript /Users/ME/Code/PROJECT/Pods/ReactiveObjC/ReactiveObjC/RACCompoundDisposableProvider.d (in target 'ReactiveObjC')

**Comment by liscio** [comment]
Have you tried the legacy build system? I found this to be a problem when using the new (Preview) build system that shipped with Xcode 9. It can't seem to deal with DTrace scripts correctly.

**Comment by Jinzhengxuan** [comment]
yes, @liscio , when I change build system to [standard build system], the error disappear.
