### ISSUE TITLE
switchToLatest completes if signal of signals sends error

### ISSUE THREAD

**Issue by adc-amatosov** [ReactiveCocoa/ReactiveObjC#127]
I have a signal of signals that from time to time gets an a signal which has error in it.
I have tried using switchToLatest to have a subscription on this signal of signals and was expecting that error will go in, but will not complete the signal created by switchToLatest.
From `switchToLatest` inline docs:
```
Returns a signal which passes through `next`s and `error`s from the latest signal sent by the receiver, and sends `completed` when both the receiver and the last sent signal complete.
```

Here is the code that reproduces the issue:
```
RACSubject *subject = [RACSubject subject];

[[[subject switchToLatest]
    catchTo:[RACSignal return:@-1]]
    subscribeNext:^(NSNumber *status)
    {
        NSLog(@"status: %@", status);
    }
        completed:^
        {
            NSLog(@"'switchToLatest' completed");
        }];

[subject sendNext:[RACSignal return:@1]];
[subject sendNext:[RACSignal return:@2]];
[subject sendNext:[RACSignal empty]];
[subject sendNext:[RACSignal return:@3]];
[subject sendNext:[RACSignal error:nil]];
[subject sendNext:[RACSignal return:@4]];
```

Output:
```
status: 1
status: 2
status: 3
status: -1
'switchToLatest' completed
```
My expectation was that I should get `status: 4` instead of `'switchToLatest' completed`

**Comment by mdiep** [comment]
This is working as the documentation describes.

> Returns a signal which passes through … `error`s from the latest signal

When you send `[RACSignal error:nil]`, then the `switchToLatest` sends an error—just as the documentation describes. But then you have a `catchTo:` after the `switchToLatest` that converts the error into a `-1` and lets it complete.

**Comment by adc-amatosov** [comment]
I see the same behavior if I remove `catchTo`
```
        RACSubject *subject = [RACSubject subject];

        [[subject switchToLatest]
            subscribeNext:^(NSNumber *status)
            {
                NSLog(@"status: %@", status);
            }
                    error:^(NSError *error)
                    {
                        NSLog(@"'switchToLatest' error");
                    }
                completed:^
                {
                    NSLog(@"'switchToLatest' completed");
                }];
```

Outputs:
```
status: 1
status: 2
status: 3
'switchToLatest' error
```

After spending more time on this issue I think there is no way around it as error always completes the signal. And since `switchToLatest` just wraps `flattenMap:` inside it gets completed once error is returned from the flattenMapped signal.

**Comment by adc-amatosov** [comment]
I have worked around with custom `switchToLatest` which adds `[x catchTo:[RACSignal empty]]`  for the signal that is getting unwrapped. This worked for my specific case since I didn't need errors to be passed, I needed signal to survive after errors

**Comment by mdiep** [comment]
You should be able to achieve what you want like this:

```objc
[[subject
    map:^(RACSignal *inner) {
        return [signal catchTo:[RACSignal empty]]
    }]
    switchToLatest]
```
