### ISSUE TITLE
Issue: This block declaration is not a prototype

### ISSUE THREAD

**Issue by BoxDengJZ** [ReactiveCocoa/ReactiveObjC#131]
For the code following: In RACSignal.h ,

- (RACSignal *)reduceEach:(id _Nullable (^)())reduceBlock RAC_WARN_UNUSED_RESULT;
(id _Nullable (^)())

Xcode reports a error:

This block declaration is not a prototype

Multiple parameters could be put in the reduceBlock(). As the code following: In UIAlertView+RACSignalSupport.m , and others ,

- (RACSignal *)rac_buttonClickedSignal {
    RACSignal *signal = [[[[self.rac_delegateProxy
        signalForSelector:@selector(alertView:clickedButtonAtIndex:)]
        reduceEach:^(UIAlertView *alertView, NSNumber *buttonIndex){
            return buttonIndex;
        }]
    ......
    return signal;
}
Kinda generic. I think I can put zero or more parameters in the block, with void (^block)() declared.

The syntax is not supported now in Xcode. 
Hope you can solve it.

Here is the StackOverFlow [question link ](https://stackoverflow.com/questions/47916585/objective-c-block-parameter-issue-this-block-declaration-is-not-a-prototype)

**Comment by andersio** [comment]
We are going to release a patch version for this.

**Comment by mdiep** [comment]
https://github.com/ReactiveCocoa/ReactiveObjC/releases/tag/3.1.0
