### ISSUE TITLE
ReactiveObjC 3.1.0 doesn't install via CocoaPods

### ISSUE THREAD

**Issue by miklselsoe** [ReactiveCocoa/ReactiveObjC#132]
It seems like the 3.1.0 release is not properly propagated for use with CocoaPods. Even after running `pod repo update`, version 3.1.0 cannot be installed. This is what I see after running pod install (version being set to 3.1.0 in podfile):

```
[!] Unable to satisfy the following requirements:

- `ReactiveObjC (~> 3.1.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `ReactiveObjC (~> 3.1.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

**Comment by andersio** [comment]
I did ask the pod owners to push 3.1.0 A’s I do not have the permission. Hopefully it would happen soon as holiday ends.

**Comment by erichoracek** [comment]
@andersio I pushed 3.1.0 to the CocoaPods specs repo and made you an owner as well—let me know if there's anyone else I should add. Thanks for cutting this release!

**Comment by erichoracek** [comment]
@miklselsoe Please try again after a `pod repo update`—you should be able to install 3.1.0 now. Thanks for letting us know about this!
