### ISSUE TITLE
Use Cocoapods: "pod search ReactiveObjC" not find the ReactiveObjC

### ISSUE THREAD

**Issue by kyfn** [ReactiveCocoa/ReactiveObjC#133]

**Comment by ikesyo** [comment]
Maybe you should run `pod repo update`.

**Comment by kyfn** [comment]
@ikesyo I'm updated cocoapods but the problem still exists.

**Comment by ikesyo** [comment]
I can't reproduce it locally unfortunately.

Could you please make it sure that you use the latest CocoaPods (1.3.0) and also update the specs repository.

```shell
$ gem update cocoapods
$ pod repo update
```

**Comment by kyfn** [comment]
@ikesyo Thanks, My pod version is 1.4.0.rc.1, maybe the version is not supprot ReactiveObjC.
