### ISSUE TITLE
iOS9.3.5 无法监听 TextField的text 变化,以及监听 Button 的点击事件

### ISSUE THREAD

**Issue by zeroffei** [ReactiveCocoa/ReactiveObjC#134]
[[button rac_signalForControlEvents:UIControlEventTouchUpInside] subscribeNext:^(__kindof UIControl * _Nullable x) {
     
  //在 iOS9.3.5 这个 block块不执行
        }];

**Comment by faimin** [comment]
are you sure your button is not nil ?

**Comment by zeroffei** [comment]
I am sure button is not nil. Now,i have solved the problem. The reason for this problem is that the ReactiveObjC version is too high, and the problem version is 3.1.0, and the system is iOS 9.3.5.Therefore, i can drop to the 2.5 version and i can click normally. After ,finally ,thank you very much for your reply!
发自我的 iPhone
