### ISSUE TITLE
About generic.

### ISSUE THREAD

**Issue by longjianjiang** [ReactiveCocoa/ReactiveObjC#135]
```
@interface RACCommand<__contravariant InputType, __covariant ValueType> : NSObject
```

Help, why `RACCommand` InputType use `__contravariant`  rather than `__covariant`, as same as ValueType?

**Comment by longjianjiang** [comment]
@andersio

**Comment by mdiep** [comment]
Because functions are contravariant in their inputs and covariant in their outputs. https://en.wikipedia.org/wiki/Covariance_and_contravariance_(computer_science)#Function_types
