### ISSUE TITLE
In "- (RACSignal<NSNotification *> *)rac_addObserverForName:(nullable NSString *)notificationName object:(nullable id)object;",if the object is not nil, the notification's block will not be called.

### ISSUE THREAD

**Issue by XTShow** [ReactiveCocoa/ReactiveObjC#136]
First of all, thank you very much for providing us with such a great framework！
When I use the "- (RACSignal<NSNotification *> *)rac_addObserverForName:(nullable NSString *)notificationName object:(nullable id)object;", for example:
````
[[[[NSNotificationCenter defaultCenter] rac_addObserverForName:UIApplicationDidEnterBackgroundNotification object:nil] takeUntil:[self rac_willDeallocSignal]] subscribeNext:^(NSNotification * _Nullable x) {
        NSLog(@"%@",x);
    }];
````
the "object" must be nil, when the app enter background, the block will be called。
But when the object not nil，like @"asd" ,self, the block will not be called.
Is the way I use it wrong?

**Comment by mdiep** [comment]
I'd suggest looking at the documentation for [the `NSNotificationCenter` method](https://developer.apple.com/documentation/foundation/nsnotificationcenter/1415360-addobserver?language=objc). It seems like you might be a little confused about the role of the `object` parameter.

**Comment by XTShow** [comment]
@mdiep emmmm....Yes, I confused this object and the context in KVO....This is my fault. Thank you very much!
