### ISSUE TITLE
Why the code is different ? 

### ISSUE THREAD

**Issue by bingchenqin** [ReactiveCocoa/ReactiveObjC#140]
Hi, I meet some problem, and I don`t know why.
`    RAC(namelabel,text) =RACObserve(self,vcname);`
 `   _vcname =@"11";`
when I use _vcname above the RAC line, the label shows the num "11", but when I put it below, it shows nothing.

When I use 'self.vcname' instead of _vcname, both above and below have the correct label showing @"11".

Thank you for applying me.

**Comment by StatusReport** [comment]
Accessing a field directly doesn't trigger KVO (and `RACObserve` in return), while accessing a property does.

**Comment by ikesyo** [comment]
Thanks for answering @StatusReport. Yes this is expected behavior, closing.
