### ISSUE TITLE
Extension of a generic Objective-C class cannot access the class's generic parameters at runtime

### ISSUE THREAD

**Issue by amol-patil31** [ReactiveCocoa/ReactiveObjC#163]
I have Xcode 10.1 and updated Reactive libraries as below :
Using ReactiveCocoa (9.0.0)
Using ReactiveObjC (3.1.1)
Using ReactiveSwift (5.0.1)
Using Result (4.1.0)

Below is my extension on RACSignal : 
extension RACSignal {
     public func toSignalProducer() -> SignalProducer<AnyObject?, NSError> {
            return SignalProducer { observer, disposable in
.
.
.            
}  }  }
We are getting this error after updating libraries : **Extension of a generic Objective-C class cannot access the class's generic parameters at runtime**

Is any one faced same issue after library updation and found any workaround ?

**Comment by MarcSteven** [comment]
@amolpict-ios  For the swift project, you can use ReactiveCocoa
