### ISSUE TITLE
RACObserve Expected ';' after expression

### ISSUE THREAD

**Issue by y0unghe** [ReactiveCocoa/ReactiveObjC#22]
So I am trying to create a new email signal, but getting error: "Expected ';' after expression".

```
- (instancetype)init {
    self = [super init];
    if (self) {
        RACSignal *emailSignal = RACObserve(self, email);
    }
    return self;
}
```

**Comment by erikprice** [comment]
This code works fine for me. Did you import the ReactiveCocoa header?

**Comment by y0unghe** [comment]
@erikprice Yes, I did.

I don't know why, but this worked:

`    RAC(self.viewModel, email) = [self.loginField rac_textSignal]; `

**Comment by rsenerol** [comment]
Anytime I use RACObserve macro, I'm also getting the error: "Expected ';' after expression". My Xcode version is 7.3.1 and ReactiveObjC v1.0.1 installed using cocoapod.

Seems like there is something going in NSObject+RACPropertySubscribing.h - line 63

<img width="957" alt="screen shot 2016-11-03 at 8 45 28 pm" src="https://cloud.githubusercontent.com/assets/2650072/19990754/7ee4190c-a206-11e6-9a70-7232202e5451.png">

**Comment by mdiep** [comment]
Have you tried using Xcode 8? I think there may have been a change that was required.

**Comment by rsenerol** [comment]
I have not. I ended up using ReactiveCocoa v2.5 for now. I will come back on that once I update Xcode. Thanks!

**Comment by mxl123** [comment]
@ikesyo Why did you close this question and I did not see any solution？
