### ISSUE TITLE
'metamacros.h' file not found

### ISSUE THREAD

**Issue by 3vangelos** [ReactiveCocoa/ReactiveObjC#23]
I have ReactObjC installed via Cocoapods, when I try to build my project I get:
RACTuple.h:10:9: 'metamacros.h' file not found

Any idea on how I can fix this issue?

**Comment by mdiep** [comment]
It seems that you need to upgrade/install `sed` or something. https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2909#issuecomment-239229779 https://github.com/ReactiveCocoa/ReactiveCocoa/issues/2070

**Comment by 3vangelos** [comment]
Thanks @mdiep, I had checked those. What finally worked was to enable to search user paths in the Pods project settings.

**Comment by phucdanghuu** [comment]
Worked on my project if enable to search user paths in the Pods project settings
