### ISSUE TITLE
Tagged release and a prebuilt binary for Carthage?

### ISSUE THREAD

**Issue by erichoracek** [ReactiveCocoa/ReactiveObjC#3]
Not sure about the versioning schema you'd like to use (e.g. is this ReactiveObjC `1.0`, or `2.6`), but it would be nice to be able to include this repo via Carthage alongside a prebuilt framework.

Thanks for separating this out!

**Comment by mdiep** [comment]
Yes! We need to verify that this repo has everything it needs. I'm hoping to take another look at it this week, but if you've verified that it works in your code, that'd be a huge help.

I'm not sure what to do for the version numbers of this repo. Anyone have an opinion about what's the best option?

**Comment by erichoracek** [comment]
@mdiep if this is just a direct copy of the [2.x-maintenance branch](https://github.com/ReactiveCocoa/ReactiveCocoa/tree/2.x-maintenance) from ReactiveCocoa, it should be fine for us, since that's what we're currently including in our codebase. Have there been any significant changes from that branch?

**Comment by mdiep** [comment]
I ended up making this branch from the `master` branch of ReactiveCocoa. It should be mostly the same, but it (a) adds watchOS and tvOS and (b) removes a few deprecated items.

Would you mind trying it out?

**Comment by erichoracek** [comment]
Sure—we'll take a stab it integrating it and report back if we encounter any issues.

**Comment by mdiep** [comment]
https://github.com/ReactiveCocoa/ReactiveObjC/releases/tag/1.0.0

**Comment by erichoracek** [comment]
@mdiep Thanks! Any chance of a prebuilt binary being uploaded as a release attachment?

**Comment by mdiep** [comment]
Done!
