### ISSUE TITLE
UIImagePickerController+RAC and AppStore submission

### ISSUE THREAD

**Issue by ignatovSA** [ReactiveCocoa/ReactiveObjC#31]
Due to new iTunesConnect rules, new uploaded builds would be rejected for privacy-sensitive data access, if these are not specified in app's info.plist.

ReactiveObjC users would be rejected because of missing `NSPhotoLibraryUsageDescription`.
This happens due to `UIImagePickerController+RACSignalSupport.h`, which uses `UIImagePickerController`.
This happens even if this category isn't used in project, only existence of files is enough.

It's important because developers should not be forced to include privacy descriptions which they don't use.

Simple removing
`#import <ReactiveObjC/UIImagePickerController+RACSignalSupport.h>`
from `ReactiveObjC.h` file doesn't fixes the issue.

Other frameworks examples:
https://forums.developer.apple.com/thread/62229
https://groups.google.com/forum/#!topic/google-admob-ads-sdk/UmeVUDrcDaw

**Comment by mdiep** [comment]
Please a file a radar with Apple. There's nothing we can do about this, short of removing the `UIImagePickerController` APIs.
