### ISSUE TITLE
Generic type constraint not working with map operator

### ISSUE THREAD

**Issue by altyus** [ReactiveCocoa/ReactiveObjC#40]
I've admittedly not looked deeply into lightweight generics in Objective-C, but I'm seeing an issue when changing type in a signal chain using the map operator.  

![image](https://cloud.githubusercontent.com/assets/3495711/20442242/f4f7adf8-ad95-11e6-95ef-f29e89b0514b.png)

ReactiveObjC expects the output type of the original signal rather than the mapped one, and due to the presence of the generic refuses to allow type coercion. The following results in a build error: 

![image](https://cloud.githubusercontent.com/assets/3495711/20442330/3b03a536-ad96-11e6-98e0-ee087c04625a.png)

My thought is this may be related to #34 as instancetype is picking up on the generic Signal, and that generic isn't updated with map.

**Comment by erichoracek** [comment]
@altyus Thanks for the issue report and sorry for the inconvenience. The transition to lightweight generics is just about finished. This should be fixed in #39.

**Comment by erichoracek** [comment]
As a temporary fix, I'd suggest either reverting to ReactiveObjC 1.x or casting the `rac_addObserverForName:object:` call to `RACSignal<id> *`.

**Comment by altyus** [comment]
I went with the id, just making sure I wasn't missing something.  Cheers
