### ISSUE TITLE
-[RACSignal amb:] missing

### ISSUE THREAD

**Issue by nverinaud** [ReactiveCocoa/ReactiveObjC#46]
I could not find any ["amb:"](https://msdn.microsoft.com/en-us/library/hh229115(v=vs.103).aspx) operator. Am I missing something ?

**Comment by mdiep** [comment]
Nope. ReactiveObjC doesn't have an operator like that.

**Comment by nverinaud** [comment]
Sad :(

Any suggestion for a replacement or should I create a category to add amb ?

**Comment by mdiep** [comment]
I can't think of any replacements. You'll need to create yourself. You could open a pull request to add it. I'll let other maintainers decide whether to accept an additional operator.
