### ISSUE TITLE
Sort call sequence for subscribers.

### ISSUE THREAD

**Issue by bimawa** [ReactiveCocoa/ReactiveObjC#55]
Hi guys, i'm have a question about RAC2.5
I have 3 subscribers on my signal, i'm don't know when they will be subscribed, but know one of it signals must called before other all. How can i do that on RAC2.5?

Now solve this feature with adding delay:.1 for another subscribers.

**Comment by mdiep** [comment]
I don't understand what you're trying to do. Could you explain a bit more? Giving specifics about your use case would probably help.

**Comment by bimawa** [comment]
@mdiep yea of course. I'm heave a view with header and 3 subviews after header. By default header is hidden and height ==0, and i'm heave signal for 3 subviews they catch signal and made animation. But sometimes app receive additional info where i'm must show header view subscribe it on current signal like 4th observer and catch first call for calculate header animation before other 3 subviews. After calcuation frames for header, i'm can made calculation for subviews with animations and etc. But header data subscribed last after all views, and brick all calculation sequence.  
Yea i know, its a dumb case. 
I'm just want to know its will be useless feature or not? now i fixed this case with addidng delay:.2 for  3 subviews, and no delay for header view.

**Comment by mdiep** [comment]
If you want to do things in sequence, you can use `flatMap`, `switchToLatest`, `concat`, or `then`.

```objc
[[self
    doThing1]
    then:^{
        return [RACSignal merge:@[ [self doThing2], [self doThing3] ]];
    }];
```

If you want to get all the information in parallel and then do something, you can use `zip` or `combineLatest`.

```objc
[[RACSignal
    zip:@[ [self thing1], [self thing2] ]]
    reduceEach^(id result1, id result2) {
        ...
    }];
```

You have an implicit ordering between your signals. You want to make that explicit by encoding it in the signal chain—probably using one of those two methods.

**Comment by bimawa** [comment]
@mdiep ok thank you i'll try.
