### ISSUE TITLE
RACObserve: Expected ';' after expression

### ISSUE THREAD

**Issue by BinBear** [ReactiveCocoa/ReactiveObjC#62]
I use RACObserve macro, I'm also getting the error: "Expected ';' after expression" in Xcode7.3. And ReactiveObjC v2.1.0 installed using cocoapod.But in Xcode8 is not.
![image](https://cloud.githubusercontent.com/assets/13587915/21177520/81d6ebd6-c226-11e6-8d31-d2a36aff3b29.png)

**Comment by ikesyo** [comment]
Duplicate of #22.
