### ISSUE TITLE
First release?

### ISSUE THREAD

**Issue by mhuusko5** [ReactiveCocoa/ReactiveObjC#7]
Since ReactiveObjC is just what was releasable-ReactiveCocoa, minus a bunch of stuff, it's unsurprisingly in a working/releasable state. Might it be appropriate to.. do that? :)

**Comment by mdiep** [comment]
Please see #3.

**Comment by mhuusko5** [comment]
Ah, missed that! FYI I guess this issue would be *my* answer to #3. I'm using ReactiveObjC/ReactiveSwift/ReactiveObjCBridge/ReactiveCocoa all together in a framework and a shipping app (covering Mac and iOS), and have yet to run into any problems.
