### ISSUE TITLE
Could not extend RACSignal with generic in Swift 3

### ISSUE THREAD

**Issue by NSFish** [ReactiveCocoa/ReactiveObjC#74]
Most of the code in my app is ObjC, and my Unit Test code is pure Swift. After switch from ReactiveCocoa repo to ReactiveObjC, the extension for RACSignal no longer compile. The code is something like this
```Swift
extension RACSignal {
    
    fileprivate func foo() -> RACSignal
        //...
    }
}

```
and I get error msg below:
```shell
Extension of a generic Objective-C class cannot access the class's generic parameters at runtime
```

The issue has been discussed [this proposal](https://github.com/apple/swift-evolution/blob/master/proposals/0057-importing-objc-generics.md)

I wonder is there any way to work around this other than explicitly checkout commit before [this](https://github.com/ReactiveCocoa/ReactiveObjC/pull/15/commits/24e9e534c8590ed46ad3e41b3ce029107c775f0c) ?
Thx in advance😝

**Comment by erichoracek** [comment]
Hi @NSFish, this is currently an issue with the swift compiler, please see [SR-2708](https://bugs.swift.org/browse/SR-2708).

You'll have to convert your extension to be a free function. Please see [ReactiveObjCBridge/ObjectiveCBridging.swift#L113-L138](https://github.com/ReactiveCocoa/ReactiveObjCBridge/blob/master/ReactiveObjCBridge/ObjectiveCBridging.swift#L113-L138) as an example of this in practice.

**Comment by NSFish** [comment]
Thx, this helps~
