### ISSUE TITLE
Unknown type name RACSubject, RACSignal

### ISSUE THREAD

**Issue by bo1ka** [ReactiveCocoa/ReactiveObjC#78]
Hi,

I am in dire need of help, I am working on a project started by somebody else. I just did a pod update and I have:

Installing ReactiveCocoa (5.0.1)
Installing ReactiveSwift (1.1.0)
Installing Result (3.2.1)

When I build the project i get:

<img width="1077" alt="screen shot 2017-03-08 at 13 34 30" src="https://cloud.githubusercontent.com/assets/5535679/23702465/094ecb28-0404-11e7-8b6e-0446860d7e1b.png">

Any input is much appreciated.

Adrian

**Comment by mdiep** [comment]
`RACSignal`, etc. are no longer part of https://github.com/ReactiveCocoa/ReactiveCocoa. They're now part of this project—ReactiveObjC. You'll need to use and import ReactiveObjC instead.

**Comment by bo1ka** [comment]
Thanks for the quick response.

Have a great day.
