### ISSUE TITLE
你好  我使用命令报错了

### ISSUE THREAD

**Issue by hhb19900618** [ReactiveCocoa/ReactiveObjC#8]
Failed to check out repository into /Users/huabinhu/Library/Caches/org.carthage.CarthageKit/dependencies/Quick: No object named "swift-3.0" exists

**Comment by iv-mexx** [comment]
Right, the Reference to Quick needs to be updated. But thats in the private Cartfile, what are you trying to do that you run into this?

**Comment by hhb19900618** [comment]
我体验学习一下
