### ISSUE TITLE
What's the effect of `__weak RACStream *stream __attribute__((unused)) = self;` in `flatten`

### ISSUE THREAD

**Issue by faimin** [ReactiveCocoa/ReactiveObjC#94]
![](http://olmn3rwny.bkt.clouddn.com/20170421183544_tAZp97_Screenshot.jpeg)
 What's the effect of `__weak RACStream *stream __attribute__((unused)) = self;` in the ` flatten` method of `RACStream`class, the `stream` variable unused, why not delete it ? It makes me wonder! There is a magic ?

**Comment by mdiep** [comment]
I think that may be left over from some code that was deleted.

**Comment by faimin** [comment]
@mdiep do you mean that it will not lead to memory leaks after delete the `__weak RACStream *stream __attribute__((unused)) = self;` code?

**Comment by andersio** [comment]
I don't see anything that would break or leak with or without it.

**Comment by faimin** [comment]
@andersio thank you!

**Comment by andersio** [comment]
Apparently this particular line has been removed from the codebase.
