### ISSUE TITLE
First in interval

### ISSUE THREAD

**Issue by nmccann** [ReactiveCocoa/ReactiveObjC#97]
Hi, we're looking for a way to get the first value sent in an interval, all other values sent in that interval should be ignored, and then this should repeat.

So for example (with an interval of 1 second):

```
4-(wait 0.4 second)-5-(wait 0.4 second)-6-(wait 0.4 second)-7-(wait 0.4 second)-|
would become:
4-7-|
```

This differs from throttle or buffer, because the first value should be sent right away rather than waiting for the end of the interval. 

I've found a [Stackoverflow answer](http://stackoverflow.com/a/31126146) that addresses a similar problem, although it uses a Window operator. It seems that ReactiveObjc used to have such an operator but it was [deprecated here](https://github.com/ReactiveCocoa/ReactiveCocoa/pull/616/commits/b4ca9c155b87a7bfed933e4bcc3f71ee950be528).

With the currently existing operators, is there a nice way to accomplish what we're trying to do? We've managed to do it by copying and slightly modifying the implementation of `throttle`, but that seems like a very messy way to do this.

Any help would be greatly appreciate, thank you!

**Comment by mdiep** [comment]
I don't think there's a way to do this with the built-in operators.
